### PR TITLE
Fixes the label in template section and toast opacity

### PR DESCRIPTION
**Pull request by mishushakov**
Fixes: Visible > Public
Toast opacity to 100:

Screenshot 2024-12-10 at 10 12 50

### CODE REVIEW

**Review by jakubno — CHANGES_REQUESTED** [review]
- Please add short description
- There's still header `Visibility`

**Comment by mishushakov** [comment]
What should the header be?

**Comment by mlejva** [comment]
@mishushakov change to label to either "Access" if you go with "Private"/"Public" language across dashboard and CLI or leave it as "Visibility" if you with the "Publish"/"Unpublish" language.

Once you resolve this and my comments, it should be good to!

**Review by mlejva — CHANGES_REQUESTED** [review]
I want to standardize naming across dashboard and CLI

There's a couple of things
1. The column calls it visibility. If we're going with "private"/"public", something like "Access" is better I think - "Who can access the sandbox with this template"
2. The CLI calls it publish and unpublish while dashboard calls it make private or make public

First, let's decide if we're going with "private"/"public" or "publish"/"unpublish" and then change either dashboard or CLI namings.

if we go with "Private"/"Public" language across dashboard and CLI or leave it as "Visibility" if you go with the "Publish"/"Unpublish" language.
394054727-bc31fae8-cbdd-4a96-a345-097e615ad90e

**Comment by mishushakov** [comment]
You also asked about the white border has transparency, here are the differences:

border-white/20

Screenshot 2024-12-16 at 22 21 51

border-white

Screenshot 2024-12-16 at 22 24 53

**Comment by mlejva** [comment]
> You also asked about the white border has transparency, here are the differences:
> 
> border-white/20
> 
> Screenshot 2024-12-16 at 22 21 51
> border-white
> 
> Screenshot 2024-12-16 at 22 24 53

The version without the white background looks better to me

**Review by mlejva — APPROVED** [review]

**Pull request merged**
