### PR TITLE
Added developer panel

### PR DESCRIPTION
**Pull request by mishushakov**
- Click on team dropdown > Developer
- Setting alternative API URL
- Setting alternative Billing URL
- Resetting the above to defaults (provided by env variable)

### CODE REVIEW

**Comment by mlejva** [comment]
Looks like the auth for preview URLs stopped working because it redirects to the production URL


https://github.com/user-attachments/assets/c14fae5b-9e80-49b4-ae38-bd9cf93150cd

**Comment by mishushakov** [comment]
try with username/password for now, not related to this

**Comment by mlejva** [comment]
Thanks, works now.

1. Please fix the unnecessary scrolling and broken footer
2. What's the reason to have the "Developer" button in the team dropdown and not as one of the tabs on the left? I want to better understand the thinking here
3. Please change the developer icon to something else because this icon is associated with bugs

https://github.com/user-attachments/assets/287bc7cd-edf0-4698-8017-6aabf0733e7d

**Comment by mishushakov** [comment]
1. on it
2. it's a hidden setting
3. on it

**Comment by mishushakov** [comment]
removed scrolling and made footer not-so-ugly

**Comment by mlejva** [comment]
> 2. it's a hidden setting

I get the hidden element of it it just doesn't fit well to me that it's in the team selection. Do we need to "hide" it?

**Comment by mlejva** [comment]
Great, thanks! Let's go a little bit further in the UX and:

1. Add description of what each field is for like this:
Screenshot 2024-12-06 at 1 46 10 PM

2. My understanding is that if a user changes the `API URL`, it implies they're running on a separate cluster and they should set the `E2B_DOMAIN` env var when using our SDK. I want us to show a code snippet showing that the user should set the env var. For example if `API URL` is `api.domain.com` people should set `E2B_DOMAIN=domain.com` before using our SDK. Does that make sense?

3. I find it a bit confusing that no tab on the left is selected because the developer settings is in the dropdown menu. It's just a bit inconsistent. I think we don't need to hide it.
 
Screenshot 2024-12-06 at 1 51 38 PM

**Comment by mishushakov** [comment]
updated
Screenshot 2024-12-06 at 23 31 45

**Comment by mlejva** [comment]
I pushed some minor updates. I spoke with @jakubno that we can hide the billing URL for now and it should work for users as well.

**Review by mlejva — APPROVED** [review]

**Pull request merged**
